### PR TITLE
Create Kuroblack.json

### PR DESCRIPTION
**Pull request by baraa272**
Fixed bookmarks (notifications) colour

### CODE REVIEW

**Comment by K1rakishou** [comment]
I actually don't think it's a bug I think it's supposed to be like this, I mean the color. And if somebody wants to change it they can do it manually with their copy of the theme.

**Comment by baraa272** [comment]
It's up to you but more people might actually report this as "notifications not working" so that's that 
I only want to help to improve this app since it's the best one for Android 11 and up

**Comment by K1rakishou** [comment]
Well I guess why not, but then I think the new color doesn't really fit this theme, maybe it should be the color of quotes - "#CC0000"? The bottom one is #CC0000

image

**Comment by baraa272** [comment]
I think it's pretty good and fitting

**Comment by baraa272** [comment]
Can I ask a question?

**Comment by baraa272** [comment]
IMG_20210529_160034
Anyway to fix this issue even after disabling (mark seen posts) this space is still there ??

**Comment by K1rakishou** [comment]
You can't remove that completely for now because it's also used by filters.

Also, I'm gonna close this PR since I think it would be better to leave the color as is. If someone wants to change it he can do it locally.

**Pull request closed without merging**
