### PR TITLE
Create EverySynth70-dark.json

### PR DESCRIPTION
**Pull request by lkd70**

### CODE REVIEW

**Comment by K1rakishou** [comment]
I think the back_color_secondary doesn't look good.

image

**Comment by lkd70** [comment]
Thanks, I didn't realise the usage of this colour for catalog grid view in the beta versions. Will update.

**Comment by K1rakishou** [comment]
Well, it's impossible to distinguish regular posts from posts marked as your own but this may be intentional, I dunno. If it's fine then I will merge it.

image

**Comment by bside-luke** [comment]
It was first a mistake but having used it for the past day I've grown to like this. I'd say stick with it unless you or others diagaree.

**Comment by lkd70** [comment]
It was first a mistake but having used it for the past day I've grown to like this. I'd say stick with it unless you or others diagaree.

**Pull request merged**
